DROP DATABASE IF EXISTS CHATDB;
CREATE DATABASE IF NOT EXISTS CHATDB;

USE CHATDB;

CREATE TABLE Users(
    UID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    USERNAME VARCHAR(45),
    PASSWORD VARCHAR(45),
    FIRSTNAME VARCHAR(45),
    LASTNAME VARCHAR(45),
    PREFNAME VARCHAR(45),
    SHORTTERM BOOLEAN,
    LONGTERM BOOLEAN,
    GPA DOUBLE,
    YEAR INT
);

CREATE TABLE Chatrooms(
    CID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NAME VARCHAR(45),
    PRIVATE BOOLEAN,
    PASSWORD VARCHAR(45)
);

CREATE TABLE Classes(
    CID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NAME VARCHAR(45)
);

CREATE TABLE Enrollments(
    UID INT,
    CID INT,
    FOREIGN KEY (UID) REFERENCES Users(UID),
    FOREIGN KEY (CID) REFERENCES Classes(CID)
);

CREATE TABLE Chatters(
    CID INT,
    UID INT,
    FOREIGN KEY (CID) REFERENCES Chatrooms(CID),
    FOREIGN KEY (UID) REFERENCES Users(UID)
);

CREATE TABLE FriendRequests(
    SENDER INT,
    RECEIVER INT,
    STATUS VARCHAR(20),
    FOREIGN KEY (SENDER) REFERENCES Users(UID),
    FOREIGN KEY (RECEIVER) REFERENCES Users(UID)
);

CREATE TABLE Friends(
    UID INT,
    FUID INT,
    FOREIGN KEY (UID) REFERENCES Users(UID),
    FOREIGN KEY (FUID) REFERENCES Users(UID)
);